"""tabele [users] add <avatar_hash>

Revision ID: 595141c7ba33
Revises: c79ca4748ba6
Create Date: 2018-12-22 15:24:59.995012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '595141c7ba33'
down_revision = 'c79ca4748ba6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
